### ISSUE TITLE
[bug] trigger date de dernière mise à jour du référentiel

### ISSUE THREAD

**Issue by AnthonyDEBUR** [AnthonyDEBUR/libreSQEbdd#3]
Le trigger suivant devrait mettre à jour la ligne qui correspond au nom de la table (et seulement celle-ci).

Quand le trigger est exécuté il écrase toutes les valeurs de la colonne ts_table en les remplaçant par le nom de la table dont la mise à jour a appelé le trigger (et il met à jour les dates avec la date du jour).

-- trigger for refer ts_suivi_maj_refer()
/* permet d'acualiser la date de dernière mise à jour d'une table du schéma réfer
 * dans la table sqe.ts_suivi_maj_refer
 */ 
CREATE OR REPLACE FUNCTION sqe.fn_update_date_refer() RETURNS TRIGGER AS
$$
DECLARE
        sql TEXT;
BEGIN
  sql := format('UPDATE sqe.ts_suivi_maj_refer SET (ts_table, ts_date) =(''%s'', now()::date)', TG_ARGV[0]);
    EXECUTE sql USING NEW;
    RETURN new;
END;
$$
language plpgsql;

**Comment by AnthonyDEBUR** [comment]
Dans la requête SQL 
sql := format('UPDATE sqe.ts_suivi_maj_refer SET (ts_table, ts_date) =(''%s'', now()::date)', TG_ARGV[0]);
est-ce qu'il ne manquerait pas un select where ?

**Comment by cedricbriandgithub** [comment]
Oui il y a un pb de version. C'est un code intermédiaire. Regarde mes commits dans history.

________________________________
